curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/79 > problems/79
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/80 > problems/80
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/81 > problems/81
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/82 > problems/82
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/83 > problems/83
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/84 > problems/84
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/85 > problems/85
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/86 > problems/86
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/87 > problems/87
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/88 > problems/88
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/89 > problems/89
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/90 > problems/90
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/91 > problems/91
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/92 > problems/92
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/93 > problems/93
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/94 > problems/94
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/95 > problems/95
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/96 > problems/96
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/97 > problems/97
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/98 > problems/98
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/99 > problems/99
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/100 > problems/100
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/101 > problems/101
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/102 > problems/102
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/103 > problems/103
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/104 > problems/104
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/105 > problems/105
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/106 > problems/106
