curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/60 > problems/60
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/61 > problems/61
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/62 > problems/62
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/63 > problems/63
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/64 > problems/64
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/65 > problems/65
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/66 > problems/66
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/67 > problems/67
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/68 > problems/68
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/69 > problems/69
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/70 > problems/70
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/71 > problems/71
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/72 > problems/72
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/73 > problems/73
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/74 > problems/74
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/75 > problems/75
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/76 > problems/76
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/77 > problems/77
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/78 > problems/78
