curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/1 > problems/1
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/2 > problems/2
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/3 > problems/3
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/4 > problems/4
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/5 > problems/5
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/6 > problems/6
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/7 > problems/7
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/8 > problems/8
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/9 > problems/9
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/10 > problems/10
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/11 > problems/11
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/12 > problems/12
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/13 > problems/13
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/14 > problems/14
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/15 > problems/15
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/16 > problems/16
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/17 > problems/17
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/18 > problems/18
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/19 > problems/19
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/20 > problems/20
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/21 > problems/21
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/22 > problems/22
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/23 > problems/23
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/24 > problems/24
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/25 > problems/25
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/26 > problems/26
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/27 > problems/27
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/28 > problems/28
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/29 > problems/29
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/30 > problems/30
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/31 > problems/31
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/32 > problems/32
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/33 > problems/33
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/34 > problems/34
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/35 > problems/35
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/36 > problems/36
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/37 > problems/37
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/38 > problems/38
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/39 > problems/39
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/40 > problems/40
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/41 > problems/41
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/42 > problems/42
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/43 > problems/43
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/44 > problems/44
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/45 > problems/45
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/46 > problems/46
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/47 > problems/47
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/48 > problems/48
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/49 > problems/49
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/50 > problems/50
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/51 > problems/51
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/52 > problems/52
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/53 > problems/53
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/54 > problems/54
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/55 > problems/55
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/56 > problems/56
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/57 > problems/57
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/58 > problems/58
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/59 > problems/59
