curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/60 > problems/60
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/61 > problems/61
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/62 > problems/62
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/63 > problems/63
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/64 > problems/64
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/65 > problems/65
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/66 > problems/66
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/67 > problems/67
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/68 > problems/68
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/69 > problems/69
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/70 > problems/70
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/71 > problems/71
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/72 > problems/72
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/73 > problems/73
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/74 > problems/74
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/75 > problems/75
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/76 > problems/76
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/77 > problems/77
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/78 > problems/78
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/79 > problems/79
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/80 > problems/80
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/81 > problems/81
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/82 > problems/82
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/83 > problems/83
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/84 > problems/84
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/85 > problems/85
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/86 > problems/86
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/87 > problems/87
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/88 > problems/88
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/89 > problems/89
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/90 > problems/90
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/91 > problems/91
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/92 > problems/92
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/93 > problems/93
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/94 > problems/94
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/95 > problems/95
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/96 > problems/96
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/97 > problems/97
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/98 > problems/98
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/99 > problems/99
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/100 > problems/100
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/101 > problems/101
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/102 > problems/102
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/103 > problems/103
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/104 > problems/104
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/105 > problems/105
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/106 > problems/106
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/107 > problems/107
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/108 > problems/108
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/109 > problems/109
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/110 > problems/110
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/111 > problems/111
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/112 > problems/112
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/113 > problems/113
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/114 > problems/114
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/115 > problems/115
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/116 > problems/116
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/117 > problems/117
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/118 > problems/118
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/119 > problems/119
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/120 > problems/120
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/121 > problems/121
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/122 > problems/122
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/123 > problems/123
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/124 > problems/124
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/125 > problems/125
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/126 > problems/126
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/127 > problems/127
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/128 > problems/128
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/129 > problems/129
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/130 > problems/130
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/131 > problems/131
curl -H "Authorization: Bearer $YOUR_API_TOKEN" https://poses.live/api/problems/132 > problems/132
